apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-hello-world-argo-depl
spec:
  replicas: 0
  selector:
    matchLabels:
      app: react-hello-world-argo
  template:
    metadata:
      labels:
        app: react-hello-world-argo
    spec:
      containers:
      - name: react-hello-world-argo-app
        image: somnathbm/react-hello-world-argo:yellow
        ports:
        - containerPort: 80
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello-world-app-rollout
spec:
  replicas: 2
  analysis:
    successfulRunHistoryLimit: 5
    unsuccessfulRunHistoryLimit: 5
  
  selector:
    matchLabels:
      app: react-hello-world-argo
  
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: react-hello-world-argo-depl
    scaleDown: progressively
    
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 0
      canaryService: hello-world-app-rollout-canary
      stableService: hello-world-app-rollout-stable
      steps:
      - setWeight: 10
      - pause:
          duration: 10s
      - setWeight: 20
      - pause:
          duration: 20s
      - setWeight: 30
      - pause:
          duration: 30s
      - setWeight: 50
        pause:
          duration: 60s
      - setWeight: 100