apiVersion: v1
kind: Service
metadata:
  name: argo-app-svc
  namespace: argocd
  labels:
    cd_type: argocd
spec:
  selector:
    app: nginx-app
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-deploy
  namespace: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80