name: Manifest change trigger
run-name: Manifest change trigger

on:
  repository_dispatch:
    types: [react-hello-test]

jobs:
  manifest-change:
    if: ${{github.event.client_payload.passed}}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Setup git config
      run: |
        git config --global user.email "somnathbm0@gmail.com"
        git config --global user.name "somnathbm"
    - name: Modify the manifest file
      run: |
        sed -i"" -E "s/somnathbm/react-hello-world-argo:.*/somnathbm/react-hello-world-argo:${{github.event.client_payload.selectedColor}}/i" hello-world-argo-rollout.yaml
        git add .
        git commit -m "changed the image to ${{github.event.client_payload.selectedColor}}"
        git push